[Stdlib] Use multi-line message in `assert_equal` for readability (#31371)
A small change, but IMO makes assertions much more visually scannable
and consistent.

If folks like this I'll make the same change to `assert_not_equal`.

**Before:**

```
  2> assert_equal("Hello", "World") 
  3.  
Error: AssertionError: Hello is not equal to World
```

**After:**

```
  2> assert_equal("Hello", "World") 
  3.  
Error: AssertionError: `left == right` comparison failed:
   left: Hello
  right: World
```

modular-orig-commit: 619c32344b54493ff5564dde1e8b3eaba89b4a59