[mojo-stdlib] Ensure size of `StaticTuple` is >= 0 (#30139)
Currently, users can try to instantiate a `StaticTuple[-1, some_type]` which
fails when instantiating the underlying MLIR type with a negative size like so:

```
error: static_tuple.mojo:72:10: error: 'pop.array.repeat' op requires a
non-negative size
```

This isn't very user-friendly.  Instead, specify the class parameter constraints
earlier in the library and provide a user-friendly error message about the arity
requirements.

In the future, we could look into a few things:
1) Investigate our type domains so we don't just use `Int` everywhere when
   sometimes we really mean unsigned only (like in the tuple case, but similarly
   with `Array` for example).
2) Extend the stdlib test suite to have "compile-time failure" tests, similar to
   `libc++` where we validate the error message presented when rejecting code.
   This isn't super high priority, but is useful over time.  In this case, the
   constraint is trivial.
3) Introduce `constrained` as a language construct so that it can be
   used at a struct level scope.  Right now, `constrained` is a library
   function and cannot be called at struct level scope to enforce class-level
   constraints.  Users wanting to write code like `static_assert` equivalent
   are forced to put it into a function and call it within each of the
   constructors, which is a bit verbose.

Fixes [Internal Link]

modular-orig-commit: 1f715c80f2b5bf820e66210a721d4f8e0810d60c