[Stdlib] Do not use recursive functions for getitem, NFC (#33253)
Somehow causes

```
📝 "RetinaNet" execution on "****":
⏱️ Finished running retinanet-static using stock-onnxruntime in 1.06s
ERROR    Failed to execute (status 1):

         COMMAND: /home/jjgalvez/modular/.derived/build/bin/mt --model-inputs=zeros --num-threads=0 --num-runs=1 --print-precision=15 --result-output-style=binary --binary-output-dir=/tmp/tmpzn2utrrn --result-output-style=binary --execute --input-shapes=3x1024x1024
         /home/jjgalvez/modular/.derived/models/****/retinanet-static.****
         STDERR:
         loc("/home/jjgalvez/modular/Kernels/mojo/stdlib/collections/vector.mojo":534:8): error: function has recursive call to 'always_inline' function
         loc("/home/jjgalvez/modular/Kernels/mojo/****/****.mojo":1:1): error: failed to run the pass manager
         loc("/home/jjgalvez/modular/.derived/models/****/retinanet-static.****":0:0): error: Elaboration failed
         loc("/home/jjgalvez/modular/Kernels/mojo/stdlib/collections/vector.mojo":534:8): error: function has recursive call to 'always_inline' function
         loc("/home/jjgalvez/modular/Kernels/mojo/****/****.mojo":1:1): error: failed to run the pass manager
         loc("/home/jjgalvez/modular/.derived/models/****/retinanet-static.****":0:0): error: Elaboration failed
         loc("/home/jjgalvez/modular/.derived/models/****/retinanet-static.****":0:0): error: operand #0 does not dominate this use
         /home/jjgalvez/modular/.derived/build/bin/mt: Model compilation failed
```

which makes 0 sense because the function was not inlined to begin with

See [Internal Link]

modular-orig-commit: 5e36bc050c2b8ddde5367e188fb24c41825d6eac